services:
  - type: web
    name: ib-google
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app:app --host 0.0.0.0 --port $PORT"
    healthCheckPath: /healthz
    envVars:
      - key: NOTION_TOKEN
        sync: false
      - key: NOTION_DB_ID
        sync: false
